camunda:
  bpm:
    admin-user:
      id: demo
      password: demo
    filter:
      create: All Tasks
    authorization:
      enabled: true
    generic-properties:
      properties:
        historyTimeToLive: "P180D"
    webapp:
      header-security:
        content-security-policy-value: font-src 'self' data:;
#    webapp:
#      application-path: /
spring:
  profiles:
    active: local

## Server configuration for reverse proxy (HTTPS)
server:
  forward-headers-strategy: native
  compression:
    enabled: true

springdoc:
  swagger-ui:
    enabled: true
    path: /config
    disable-swagger-default-url: true
    urls-primary-name: Classroom API
    urls:
      - name: Camunda REST API
        url: /camunda-rest/openapi.json
#  jersey:
#    application-path: /rest
#  datasource:
#    url: jdbc:h2:file:./data/camunda
#    username: sa
#    password: sa
## Uncomment the following lines to enable the h2 DB console:
#  h2:
#    console:
#      enabled: true
#      path: /console

## Uncomment the following lines to change to port number:
#server:
#  port: 8081